# Stable

edition = "2021"

match_block_trailing_comma = true
use_field_init_shorthand = true
use_try_shorthand = true

# Nightly

condense_wildcard_suffixes = true
format_strings = true
imports_layout = "horizontalvertical"
imports_granularity = "crate"
reorder_impl_items = true